#!/usr/bin/env bun
import { codexStubMain } from "../../lib/app-server.js";
const code = codexStubMain(process.argv);
if (typeof code === "number") process.exit(code);
// null = app-server mode: keep the process alive
